import pygame

WINDOW_WIDTH = 550
WINDOW_HEIGHT = 600
CELL_SIZE = 60

BOARD_SIZE = 9
BLANK_COUNT = 40
FONT_NAME = "Arial"
FONT_SIZE = 30
PLAY_AGAIN_FONT_SIZE = 46
VISUALIZATION_DELAY_MS = 100

COLOR_GRAY = (128, 128, 128)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0,0,205)
COLOR_GREEN = (0, 255, 0)

TIME_TEXT_POSITION = (380, 560)
STRIKES_TEXT_POSITION = (20, 560)
TK_TOPMOST_ATTRIBUTE = "-topmost"

CELL_BORDER_WIDTH = 3

MUSIC_PATH = "resources/music.mp3"
CLICK_SOUND_PATH = "resources/click.wav"
CORRECT_SOUND_PATH = "resources/correct.wav"

GAME_BANNER = "Sudoku Solver: by Arian"
PLAY_AGAIN_MESSAGE = "Play again? (Y/N)"

RESET_KEY = pygame.K_r
SOLVE_KEY = pygame.K_SPACE
QUIT_EVENT = pygame.QUIT
PLAY_AGAIN_YES = pygame.K_y
PLAY_AGAIN_NO = pygame.K_n